### ISSUE TITLE
accounts crate: Implement a deployContract function

### ISSUE THREAD

**Issue by jaswinder6991** [Harmonic-Guild/near-api-rs#14]
Implement a deployContract function in accounts crate similar to the JS [implementation](https://github.com/near/near-api-js/blob/master/packages/accounts/src/account.ts#L379).

Code snippet
```
/**
     * @param data The compiled contract code
     */
    async deployContract(data: Uint8Array): Promise<FinalExecutionOutcome> {
        return this.signAndSendTransaction({
            receiverId: this.accountId,
            actions: [deployContract(data)]
        });
    }
```

**Comment by kiran3807** [comment]
Looking into this

**Comment by jaswinder6991** [comment]
> Looking into this

Thanks Kiran for this interest. This has been done already by Kshitij.
